download-data:
	wget ftp://guest:GU.205dldo@ftp.softronics.ch/mvtec_anomaly_detection/mvtec_anomaly_detection.tar.xz
	xz -dv mvtec_anomaly_detection.tar.xz
	tar xfv mvtec_anomaly_detection.tar
	rm -f mvtec_anomaly_detection
